#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica5
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TicketMania")]
	public partial class TPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertComentarios(Comentarios instance);
    partial void UpdateComentarios(Comentarios instance);
    partial void DeleteComentarios(Comentarios instance);
    partial void InsertActividades(Actividades instance);
    partial void UpdateActividades(Actividades instance);
    partial void DeleteActividades(Actividades instance);
    partial void InsertReservas(Reservas instance);
    partial void UpdateReservas(Reservas instance);
    partial void DeleteReservas(Reservas instance);
    #endregion
		
		public TPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Comentarios> Comentarios
		{
			get
			{
				return this.GetTable<Comentarios>();
			}
		}
		
		public System.Data.Linq.Table<Actividades> Actividades
		{
			get
			{
				return this.GetTable<Actividades>();
			}
		}
		
		public System.Data.Linq.Table<Reservas> Reservas
		{
			get
			{
				return this.GetTable<Reservas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentarios")]
	public partial class Comentarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdComentario;
		
		private string _DNI;
		
		private string _NombreCompleto;
		
		private string _Comentario;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<int> _IdReserva;
		
		private EntityRef<Reservas> _Reservas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdComentarioChanging(int value);
    partial void OnIdComentarioChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnNombreCompletoChanging(string value);
    partial void OnNombreCompletoChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnIdReservaChanging(System.Nullable<int> value);
    partial void OnIdReservaChanged();
    #endregion
		
		public Comentarios()
		{
			this._Reservas = default(EntityRef<Reservas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComentario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdComentario
		{
			get
			{
				return this._IdComentario;
			}
			set
			{
				if ((this._IdComentario != value))
				{
					this.OnIdComentarioChanging(value);
					this.SendPropertyChanging();
					this._IdComentario = value;
					this.SendPropertyChanged("IdComentario");
					this.OnIdComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this.OnNombreCompletoChanging(value);
					this.SendPropertyChanging();
					this._NombreCompleto = value;
					this.SendPropertyChanged("NombreCompleto");
					this.OnNombreCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReserva", DbType="Int")]
		public System.Nullable<int> IdReserva
		{
			get
			{
				return this._IdReserva;
			}
			set
			{
				if ((this._IdReserva != value))
				{
					if (this._Reservas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdReservaChanging(value);
					this.SendPropertyChanging();
					this._IdReserva = value;
					this.SendPropertyChanged("IdReserva");
					this.OnIdReservaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservas_Comentarios", Storage="_Reservas", ThisKey="IdReserva", OtherKey="Id", IsForeignKey=true)]
		public Reservas Reservas
		{
			get
			{
				return this._Reservas.Entity;
			}
			set
			{
				Reservas previousValue = this._Reservas.Entity;
				if (((previousValue != value) 
							|| (this._Reservas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Reservas.Entity = null;
						previousValue.Comentarios.Remove(this);
					}
					this._Reservas.Entity = value;
					if ((value != null))
					{
						value.Comentarios.Add(this);
						this._IdReserva = value.Id;
					}
					else
					{
						this._IdReserva = default(Nullable<int>);
					}
					this.SendPropertyChanged("Reservas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Actividades")]
	public partial class Actividades : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdActividad;
		
		private string _NombreActividad;
		
		private int _TotalPlazas;
		
		private int _Disponible;
		
		private string _Descripcion;
		
		private EntitySet<Reservas> _Reservas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdActividadChanging(int value);
    partial void OnIdActividadChanged();
    partial void OnNombreActividadChanging(string value);
    partial void OnNombreActividadChanged();
    partial void OnTotalPlazasChanging(int value);
    partial void OnTotalPlazasChanged();
    partial void OnDisponibleChanging(int value);
    partial void OnDisponibleChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Actividades()
		{
			this._Reservas = new EntitySet<Reservas>(new Action<Reservas>(this.attach_Reservas), new Action<Reservas>(this.detach_Reservas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdActividad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdActividad
		{
			get
			{
				return this._IdActividad;
			}
			set
			{
				if ((this._IdActividad != value))
				{
					this.OnIdActividadChanging(value);
					this.SendPropertyChanging();
					this._IdActividad = value;
					this.SendPropertyChanged("IdActividad");
					this.OnIdActividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreActividad", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreActividad
		{
			get
			{
				return this._NombreActividad;
			}
			set
			{
				if ((this._NombreActividad != value))
				{
					this.OnNombreActividadChanging(value);
					this.SendPropertyChanging();
					this._NombreActividad = value;
					this.SendPropertyChanged("NombreActividad");
					this.OnNombreActividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPlazas", DbType="Int NOT NULL")]
		public int TotalPlazas
		{
			get
			{
				return this._TotalPlazas;
			}
			set
			{
				if ((this._TotalPlazas != value))
				{
					this.OnTotalPlazasChanging(value);
					this.SendPropertyChanging();
					this._TotalPlazas = value;
					this.SendPropertyChanged("TotalPlazas");
					this.OnTotalPlazasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disponible", DbType="Int NOT NULL")]
		public int Disponible
		{
			get
			{
				return this._Disponible;
			}
			set
			{
				if ((this._Disponible != value))
				{
					this.OnDisponibleChanging(value);
					this.SendPropertyChanging();
					this._Disponible = value;
					this.SendPropertyChanged("Disponible");
					this.OnDisponibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Actividades_Reservas", Storage="_Reservas", ThisKey="IdActividad", OtherKey="IdActividad")]
		public EntitySet<Reservas> Reservas
		{
			get
			{
				return this._Reservas;
			}
			set
			{
				this._Reservas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservas(Reservas entity)
		{
			this.SendPropertyChanging();
			entity.Actividades = this;
		}
		
		private void detach_Reservas(Reservas entity)
		{
			this.SendPropertyChanging();
			entity.Actividades = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservas")]
	public partial class Reservas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NombreCompleto;
		
		private string _DNI;
		
		private string _Email;
		
		private string _Telefono;
		
		private System.Nullable<System.DateTime> _FechaNacimiento;
		
		private int _IdActividad;
		
		private EntitySet<Comentarios> _Comentarios;
		
		private EntityRef<Actividades> _Actividades;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreCompletoChanging(string value);
    partial void OnNombreCompletoChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnFechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaNacimientoChanged();
    partial void OnIdActividadChanging(int value);
    partial void OnIdActividadChanged();
    #endregion
		
		public Reservas()
		{
			this._Comentarios = new EntitySet<Comentarios>(new Action<Comentarios>(this.attach_Comentarios), new Action<Comentarios>(this.detach_Comentarios));
			this._Actividades = default(EntityRef<Actividades>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCompleto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreCompleto
		{
			get
			{
				return this._NombreCompleto;
			}
			set
			{
				if ((this._NombreCompleto != value))
				{
					this.OnNombreCompletoChanging(value);
					this.SendPropertyChanging();
					this._NombreCompleto = value;
					this.SendPropertyChanged("NombreCompleto");
					this.OnNombreCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(30)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdActividad", DbType="Int NOT NULL")]
		public int IdActividad
		{
			get
			{
				return this._IdActividad;
			}
			set
			{
				if ((this._IdActividad != value))
				{
					if (this._Actividades.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdActividadChanging(value);
					this.SendPropertyChanging();
					this._IdActividad = value;
					this.SendPropertyChanged("IdActividad");
					this.OnIdActividadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Reservas_Comentarios", Storage="_Comentarios", ThisKey="Id", OtherKey="IdReserva")]
		public EntitySet<Comentarios> Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				this._Comentarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Actividades_Reservas", Storage="_Actividades", ThisKey="IdActividad", OtherKey="IdActividad", IsForeignKey=true)]
		public Actividades Actividades
		{
			get
			{
				return this._Actividades.Entity;
			}
			set
			{
				Actividades previousValue = this._Actividades.Entity;
				if (((previousValue != value) 
							|| (this._Actividades.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Actividades.Entity = null;
						previousValue.Reservas.Remove(this);
					}
					this._Actividades.Entity = value;
					if ((value != null))
					{
						value.Reservas.Add(this);
						this._IdActividad = value.IdActividad;
					}
					else
					{
						this._IdActividad = default(int);
					}
					this.SendPropertyChanged("Actividades");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentarios(Comentarios entity)
		{
			this.SendPropertyChanging();
			entity.Reservas = this;
		}
		
		private void detach_Comentarios(Comentarios entity)
		{
			this.SendPropertyChanging();
			entity.Reservas = null;
		}
	}
}
#pragma warning restore 1591
